---
engines:
  eslint-8:
    exclude_paths:
      - "test/**"
      - "eval/**"
      - "evals/**"
      - "src/core/review/jev/dashboard/public/**"
  stylelint:
    exclude_paths:
      - "src/core/review/jev/dashboard/public/**"
exclude_paths:
  - "test/**"
  - "eval/**"
  - "evals/**"
  - "src/core/review/jev/dashboard/public/**"
