/**
 * Durable E2E Regression Test Codifier.
 * Generates executable test suites for tester-army/e2e (@e2e-dev/web) to prevent visual and UX regressions.
 */

import { UIDefect } from './types.js';
import * as fs from 'fs';
import * as path from 'path';

export function generateE2ETestFileContent(
  targetUrl: string,
  resolvedDefects: UIDefect[]
): string {
  const tests = resolvedDefects.map((d, idx) => {
    const testTitle = `regression [${d.category}]: ${d.message.replace(/['"\\]/g, '')}`;
    if (d.category === 'overflow') {
      return `  test('${testTitle}', async ({ app, browser }) => {
    await app.open('${d.url || targetUrl}');
    const hasOverflow = await browser.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth);
    expect(hasOverflow).toBe(false);
  });`;
    }

    if (d.category === 'touch_target' && d.selector) {
      return `  test('${testTitle}', async ({ app, screen }) => {
    await app.open('${d.url || targetUrl}');
    const target = screen.locator('${d.selector}');
    const box = await target.boundingBox();
    expect(box?.width ?? 0).toBeGreaterThanOrEqual(44);
    expect(box?.height ?? 0).toBeGreaterThanOrEqual(44);
  });`;
    }

    // Default agentic assert check
    return `  test('${testTitle}', async ({ app, agent }) => {
    await app.open('${d.url || targetUrl}');
    await agent.assert('Ensure ${d.expected?.replace(/['"\\]/g, '') || 'UI is pristine without defects'}');
  });`;
  }).join('\n\n');

  return `// Generated by get-fable UI/UX Polish Round
// Runner: tester-army/e2e (@e2e-dev/web)
import { test } from '@e2e-dev/web';
import { expect } from 'e2e';

describe('UI/UX Polish Regression Suite', () => {
${tests || `  test('baseline accessibility and layout integrity', async ({ app, browser }) => {
    await app.open('${targetUrl}');
    const hasOverflow = await browser.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth);
    expect(hasOverflow).toBe(false);
  });`}
});
`;
}

export function writeRegressionSuite(
  projectDir: string,
  targetUrl: string,
  resolvedDefects: UIDefect[]
): string {
  const e2eDir = path.join(projectDir, 'tests', 'e2e');
  fs.mkdirSync(e2eDir, { recursive: true });

  const testFilePath = path.join(e2eDir, 'polish-regression.e2e.ts');
  const content = generateE2ETestFileContent(targetUrl, resolvedDefects);
  fs.writeFileSync(testFilePath, content, 'utf-8');

  // Also write e2e.config.ts if it does not exist
  const configPath = path.join(projectDir, 'e2e.config.ts');
  if (!fs.existsSync(configPath)) {
    const configContent = `// e2e.config.ts - Generated by get-fable
import type { E2EConfig } from 'e2e';
import { web } from '@e2e-dev/web';

export default {
  targets: [
    {
      engine: web(),
      app: {
        url: '${targetUrl}',
      },
    },
  ],
} satisfies E2EConfig;
`;
    fs.writeFileSync(configPath, configContent, 'utf-8');
  }

  return testFilePath;
}
