import fs from 'node:fs';
import path from 'node:path';

type RegistrySkill = {
  id: string;
  order: number;
  phase: string;
  pack: string;
  description: string;
};

type CanonicalRegistry = {
  schemaVersion: number;
  entry: string;
  skills: RegistrySkill[];
};

type Artifact = { path: string; content: string };

function readJson(filePath: string): any {
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

function canonicalRegistry(repoRoot: string): CanonicalRegistry {
  const filePath = path.join(repoRoot, 'skills', 'get-fable', 'registry.json');
  const value = readJson(filePath) as CanonicalRegistry;
  if (!value || value.schemaVersion !== 2 || !Array.isArray(value.skills) || value.skills.length === 0) {
    throw new Error('Canonical registry must be schemaVersion 2 with non-empty skills');
  }
  const ids = value.skills.map((skill) => skill.id);
  if (ids.some((id) => typeof id !== 'string' || !id.trim()) || new Set(ids).size !== ids.length) {
    throw new Error('Canonical registry contains invalid or duplicate skill IDs');
  }
  return value;
}

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function generatedTs(registry: CanonicalRegistry): string {
  const skills = [...registry.skills].sort((a, b) => a.order - b.order);
  const ids = skills.map((skill) => skill.id);
  const packs = [...new Set(skills.map((skill) => skill.pack))];
  const phaseLines = skills.map((skill) => `  '${skill.id}': '${skill.phase}',`).join('\n');
  const packLines = skills.map((skill) => `  '${skill.id}': '${skill.pack}',`).join('\n');
  return `// Generated by scripts/generate-catalog.ts from skills/get-fable/registry.json.\n// Do not edit by hand.\n\nexport const CANONICAL_SKILLS = ${JSON.stringify(ids, null, 2)} as const;\nexport type FableSkillId = (typeof CANONICAL_SKILLS)[number];\n\nexport const FABLE_PACKS = ${JSON.stringify(packs, null, 2)} as const;\nexport type FablePack = (typeof FABLE_PACKS)[number];\n\nexport const SKILL_PHASE = {\n${phaseLines}\n} as const;\n\nexport const SKILL_PACK = {\n${packLines}\n} as const;\n`;
}

function generatedSkillMarkdown(registry: CanonicalRegistry): string {
  const rows = [...registry.skills]
    .sort((a, b) => a.order - b.order)
    .map((skill) => `| ${skill.order} | ${skill.pack} | \`${skill.id}\` | ${skill.phase} | ${skill.description.replace(/\|/g, '\\|')} |`)
    .join('\n');
  return `# Canonical Skill Catalog\n\nGenerated from \`skills/get-fable/registry.json\` by \`bun run generate:catalog\`. Do not edit by hand.\n\n| Order | Pack | Skill | Phase | Job |\n| ---: | --- | --- | --- | --- |\n${rows}\n`;
}

function generatedPythonCatalog(registry: CanonicalRegistry): string {
  const ids = [...registry.skills]
    .sort((a, b) => a.order - b.order)
    .map((skill) => `    ${JSON.stringify(skill.id)},`)
    .join('\n');
  return `# Generated by scripts/generate-catalog.ts from skills/get-fable/registry.json.\n# Do not edit by hand.\n\nCANONICAL_SKILLS = {\n${ids}\n}\n`;
}

function generatedSkillsSh(repoRoot: string, registry: CanonicalRegistry): string {
  const currentPath = path.join(repoRoot, 'skills.sh.json');
  const current = fs.existsSync(currentPath) ? readJson(currentPath) : {};
  return json({
    ...current,
    skills: [...registry.skills]
      .sort((a, b) => a.order - b.order)
      .map((skill) => ({
        id: skill.id,
        path: `skills/${skill.id}/SKILL.md`,
        description: skill.description,
      })),
  });
}

function generatedPack(repoRoot: string, registry: CanonicalRegistry, packName: string): string {
  const filePath = path.join(repoRoot, 'packs', `${packName}.json`);
  const current = fs.existsSync(filePath) ? readJson(filePath) : { name: packName };
  const ordered = [...registry.skills].sort((a, b) => a.order - b.order);
  const skills = packName === 'full'
    ? ordered.map((skill) => skill.id)
    : ordered.filter((skill) => skill.pack === packName).map((skill) => skill.id);
  const next = { ...current, name: packName, skills };
  if (packName === 'full') {
    next.description = `Complete get-fable skill collection generated from the canonical registry (${skills.length} skills across ${new Set(ordered.map((skill) => skill.pack)).size} packs).`;
  }
  return json(next);
}

export function catalogArtifacts(repoRoot: string): Artifact[] {
  const registry = canonicalRegistry(repoRoot);
  const packNames = [...new Set(registry.skills.map((skill) => skill.pack)), 'full'];
  return [
    { path: 'src/generated/skill-catalog.ts', content: generatedTs(registry) },
    { path: 'hooks/_fable_catalog.py', content: generatedPythonCatalog(registry) },
    { path: 'docs/CANONICAL_SKILLS.md', content: generatedSkillMarkdown(registry) },
    { path: 'registry/skills.json', content: json(registry) },
    { path: 'skills.sh.json', content: generatedSkillsSh(repoRoot, registry) },
    ...packNames.map((packName) => ({
      path: `packs/${packName}.json`,
      content: generatedPack(repoRoot, registry, packName),
    })),
  ];
}

export function generateCatalogArtifacts(repoRoot: string): string[] {
  const changed: string[] = [];
  for (const artifact of catalogArtifacts(repoRoot)) {
    const filePath = path.join(repoRoot, artifact.path);
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : null;
    if (current !== artifact.content) {
      fs.writeFileSync(filePath, artifact.content, 'utf-8');
      changed.push(artifact.path);
    }
  }
  return changed;
}

export function checkCatalogArtifacts(repoRoot: string): { ok: boolean; drift: string[] } {
  const drift = catalogArtifacts(repoRoot)
    .filter((artifact) => {
      const filePath = path.join(repoRoot, artifact.path);
      return !fs.existsSync(filePath) || fs.readFileSync(filePath, 'utf-8') !== artifact.content;
    })
    .map((artifact) => artifact.path);
  return { ok: drift.length === 0, drift };
}
