# get-fable fish completion

complete -c get-fable -f
complete -c get-fable -n "__fish_use_subcommand" -a "install" -d "Install supported global integrations"
complete -c get-fable -n "__fish_use_subcommand" -a "install-antigravity" -d "Install Antigravity / Gemini target"
complete -c get-fable -n "__fish_use_subcommand" -a "install-codex" -d "Install Codex target"
complete -c get-fable -n "__fish_use_subcommand" -a "install-cursor" -d "Install Cursor target"
complete -c get-fable -n "__fish_use_subcommand" -a "install-git-hooks" -d "Install universal Git hooks"
complete -c get-fable -n "__fish_use_subcommand" -a "init" -d "Create durable project state and skills"
complete -c get-fable -n "__fish_use_subcommand" -a "route" -d "Explain workflow selection"
complete -c get-fable -n "__fish_use_subcommand" -a "spark" -d "Predict atomic next move"
complete -c get-fable -n "__fish_use_subcommand" -a "state" -d "Transition durable workflow state"
complete -c get-fable -n "__fish_use_subcommand" -a "mutation" -d "Record workspace mutation"
complete -c get-fable -n "__fish_use_subcommand" -a "card" -d "Set or clear active card"
complete -c get-fable -n "__fish_use_subcommand" -a "evidence" -d "Record typed evidence"
complete -c get-fable -n "__fish_use_subcommand" -a "doctor" -d "Validate setup and state"
complete -c get-fable -n "__fish_use_subcommand" -a "shell" -d "Print shell integration script"
complete -c get-fable -n "__fish_use_subcommand" -a "lint" -d "Verify ledger and evidence"
complete -c get-fable -n "__fish_use_subcommand" -a "status" -d "Report installation status"
complete -c get-fable -n "__fish_use_subcommand" -a "update" -d "Inspect or apply explicit updates"
complete -c get-fable -n "__fish_use_subcommand" -a "announcements" -d "Inspect data-only notices"
complete -c get-fable -n "__fish_use_subcommand" -a "redteam" -d "Execute native agentic ethical penetration audit"
complete -c get-fable -n "__fish_use_subcommand" -a "pentest" -d "Alias for redteam ethical penetration audit"
complete -c get-fable -n "__fish_seen_subcommand_from update" -a "status plan apply doctor"
complete -c get-fable -n "__fish_seen_subcommand_from announcements" -a "list show dismiss refresh"
complete -c get-fable -n "__fish_seen_subcommand_from redteam pentest" -a "scan audit verify fix status setup playbooks"
